### ISSUE TITLE
Using LDR-Importer from python API

### ISSUE THREAD

**Issue by leo-p** [le717/LDR-Importer#127]
Hi guys,
I'm trying to use the LDR-Importer directly from the python API but I can't seem to make it work.
To reproduce the issue simply create a file `test.py`:
```
import bpy
import import_ldraw.py
```
Then run it using `blender -P test.py` in CLI.

I get the following output:
```
[LDR Importer] (20:23:14.29) Retrieve LDraw path from preferences
[LDR Importer] (20:23:14.29) The current platform is mac
[LDR Importer] (20:23:14.29) The LDraw Parts Library to be used is
/Users/leo/Github/lego-assembly-helper/dataset/3D/ldraw/
Traceback (most recent call last):
  File "/Users/leo/Github/lego-assembly-helper/dataset/3D/test.py", line 2, in <module>
    import import_ldraw.py
  File "/Users/leo/Library/Application Support/Blender/2.78/scripts/addons/import_ldraw.py", line 36, in <module>
    from .src.ldcolors import Colors
SystemError: Parent module '' not loaded, cannot perform relative import
```

Any idea on what I'm doing wrong?

**Comment by leo-p** [comment]
After tinkering around a bit it appears that the line `import import_ldraw.py` from `test.py` wasn't even reached. Blender simply import the module on startup.

To avoid the error message I had to change the three following lines:
```
from .src.ldcolors import Colors
from .src.ldconsole import Console
from .src.ldprefs import Preferences
```

By adding the path where it was automatically installed, thus:
```
from io_scene_ldrimporter.src.ldcolors import Colors
from io_scene_ldrimporter.src.ldconsole import Console
from io_scene_ldrimporter.src.ldprefs import Preferences
```

Any idea on where to go from there? Do you have some documentation that I missed somewhere?

**Comment by leo-p** [comment]
Turns out you run the whole script with `bpy.ops.import_scene.ldraw(filepath="model.ldr")`.
